version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    external_links:
      - laradock_mysql
    container_name: cupom_container
    stdin_open: true
    tty: true
    environment:
        PORT: 8000
        MYSQL_ROOT_PASSWORD: root
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: 172.20.0.3:3306
        DATABASE_NAME: gstest
  