version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - db:mysql
    container_name: cupom_container
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
        PORT: 8000
        MYSQL_ROOT_PASSWORD: gspass
        DB_USERNAME: gsuser
        DB_PASSWORD: gspass
        DB_HOST: mysql
        DATABASE_NAME: gstest
  db:
    image: mysql:5.7
    restart: always
    container_name: db_container
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: gsuser
        MYSQL_PASSWORD: gspass
        MYSQL_ROOT_PASSWORD: gspass
        MYSQL_DATABASE: gstest
